name: "Perform Initial Repository Setup"

on:
  push:
    branches: [main]

jobs:
  setup:
    name: "Setup Repository"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: "Git Config"
      run: |
        git config user.email "idbot@example.com"
        git config user.name "I-D Bot"

    - name: "Update Draft Name"
      run: |
        if [ -z "$(ls draft-* rfc* 2>/dev/null | grep -v draft-todo-yourname-protocol.md)" ]; then
          echo
          echo "============================================================="
          echo
          echo "It is OK for this first build to fail."
          echo "It will succeed when you rename your draft."
          echo "The file can be renamed at:"
          echo
          echo "    https://github.com/${{github.repository}}/edit/main/draft-todo-yourname-protocol.md"
          echo
          echo "Change the name of the file and its title to start the build."
          echo "Commit the changes to the 'main' branch."
          echo
          echo "============================================================="
          echo
          exit 1
        fi
        for i in draft-*; do
          sed -i -e "s/draft-todo-yourname-protocol-latest/${i%.md}-latest/g" "$i"
          git add "$i"
        done
        if [ -n "$(git status --porcelain draft-*)" ]; then
          git commit -m "Update draft labels" draft-*
        fi

    - name: "Cleanup"
      run: |
        git rm -rf .github/workflows/setup.yml README.md
        git commit -m "Remove setup files"

    - name: "Clone the i-d-template Repo"
      run: |
        git clone https://github.com/martinthomson/i-d-template lib

    - name: "Run i-d-template Setup"
      uses: martinthomson/i-d-template@v1
      with:
        make: setup

    - name: "Push Changes"
      run: |
        git push
